### ISSUE TITLE
multiple paths in one string

### ISSUE THREAD

**Issue by yelhouti** [rollup/rollup-plugin-multi-entry#14]
Hi gus,
first of all thank you for the great plugin.
I would like to suggest an enhancement please:
semicolon separated paths in one string as input;
the reason behind this suggestion is that this plugin might be inside a chain where one of the nodes expects a string and make a transformation on it (like with ionic-app-script):
{{TMP}}->/Users/.../.tmp
and providing an array breaks the build process.
having something like "path1;path2;...;pathN" would allow the first plugin to reformat all the path then your plugin put them as different imports.
Thanks in advance for your help.
Bests

**Comment by yelhouti** [comment]
pull request added

**Comment by shellscape** [comment]
@yelhouti thanks for opening this issue a while back. we're migrating this plugin to the new plugins monorepo at https://github.com/rollup/plugins. If this issue is still valid, please reopen your issue at the new repo _and please make sure to fill out the appropriate issue template._ We're closing this issue now as part of the migration.
