### ISSUE TITLE
Issue watching new files

### ISSUE THREAD

**Issue by fredjens** [rollup/rollup-plugin-multi-entry#18]
Hei!

I run `rollup -c -w` - and it works with existing files, but it do not work when i add new files (i need to restart the watch task). Is this a bug or have I done something wrong? 😕 

Fredrik

**Comment by eventualbuddha** [comment]
[The code appears to be matching on every call to `load`](https://github.com/rollup/rollup-plugin-multi-entry/blob/514a34f56599e42c64da6145b5dfc6fe1a3bfade/index.js#L52), so I'm not sure what is going on unless either rollup or `matched` is doing some caching.

**Comment by shellscape** [comment]
thanks for opening this issue a while back. we're migrating this plugin to the new plugins monorepo at https://github.com/rollup/plugins. If this issue is still valid, please reopen your issue at the new repo _and please make sure to fill out the appropriate issue template in full._ We're closing this issue now as part of the migration.
