### ISSUE TITLE
glob string doesn't work since version 2.0.2

### ISSUE THREAD

**Issue by treeno** [rollup/rollup-plugin-multi-entry#28]
I've been using glob strings to bundle test-classes together using rollup-plugin-multi-entry 2.0.1. After reinstalling my node-mudules I recieved a newer Version 2.0.2 and since then glob strings are no longer interpreted.  At least I'm getting the following message:

Could not resolve entry (test/**/*Test.js)

**Comment by shellscape** [comment]
@treeno thanks for opening this issue a while back. we're migrating this plugin to the new plugins monorepo at https://github.com/rollup/plugins. If this issue is still valid, please reopen your issue at the new repo _and please make sure to fill out the appropriate issue template in full._ We're closing this issue now as part of the migration.
