### ISSUE TITLE
Doesn't report an error if entry module is not found

### ISSUE THREAD

**Issue by larionov** [rollup/rollup-plugin-multi-entry#35]
```js
import multiEntry from "rollup-plugin-multi-entry";

export default {
  input: ["path/not/found.js"],
  plugins: [multiEntry()]
};
```
Config above just generates an empty bundle but should report and error or at least a warning.

**Comment by shellscape** [comment]
@larionov thanks for opening this issue a while back. we're migrating this plugin to the new plugins monorepo at https://github.com/rollup/plugins. If this issue is still valid, please reopen your issue at the new repo _and please make sure to fill out the appropriate issue template in full._ We're closing this issue now as part of the migration.
