### ISSUE TITLE
Entries module resolution doesn't respect settings from resolutions plugins

### ISSUE THREAD

**Issue by larionov** [rollup/rollup-plugin-multi-entry#36]
```js
import multiEntry from "rollup-plugin-multi-entry";

export default {
  input: ["Core/module.js"],
  plugins: [
    multiEntry(),
    includePaths({
      paths: [
          path.resolve('path/to/src/'),
      ],
    }),
  ]
};
```
Not sure if the problem is with `rollup-plugin-multy-entry`, but:
Config above will not resolve `module.js` to `path/to/src/Core/module.js` and just generate an empty bundle.

**Comment by shellscape** [comment]
@larionov thanks for opening this issue a while back. we're migrating this plugin to the new plugins monorepo at https://github.com/rollup/plugins. If this issue is still valid, please reopen your issue at the new repo _and please make sure to fill out the appropriate issue template in full._ We're closing this issue now as part of the migration.
