### ISSUE TITLE
Why are default exports like `default class Foo {..}` not exported?

### ISSUE THREAD

**Issue by G-Rath** [rollup/rollup-plugin-multi-entry#38]
> Note: Default exports like export default class Foo {...} will not be exported, only named exports are allowed.

Why is this? Is it bad practice, or just an opinion of this package? (or something else?)

I'm in a situation where I'm building a typescript library, that exports both a main class, and a *bunch* of small component-like classes, that are not directly by the library (similar to `@material-ui/core`), and so am trying to figure out the best way to publish this, ideally without having to import & re-export everything in an `index.ts` file.

**Comment by eventualbuddha** [comment]
> Why is this? Is it bad practice, or just an opinion of this package? (or something else?)

I don't remember, to be honest. If I were to guess, I'd say it's because [only one such default export would be allowed by the parser](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAE2AMwIYFcA28CMBuAKFElkRQ2zgCY8g&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015&prettier=false&targets=&version=7.4.3&externalPlugins=). That means we'd have to somehow determine which one it is that you wanted, which means reading and parsing all the files matched by the glob. That's a fair amount of duplicated work. You could always build such a file yourself, since all this plugin does is build a bunch of `export * from '...';` statements.

**Comment by stropho** [comment]
I had a similar issue. Using `rollup-plugin-glob-import` . Well, I have to define the `index` file manually, but the plugin solves reexporting all the imports (including `default` export and renaming it) by a glob. Good enough for me.
