### ISSUE TITLE
/ rollup-plugin-multi-entry:entry-point Directory in public gulp JS directory

### ISSUE THREAD

**Issue by dkd-thoma** [rollup/rollup-plugin-multi-entry#45]

**Comment by dkd-thoma** [comment]
I got a corrupt directory in my public js directory in my ide called `/rollup-plugin-multi-entry:entry-point`
Even if i remove the rollup rollup-plugin-multi-entry, the directory is there and i cannot delete it, my terminal don't recognize this directory and my ide can't delete this.

**Comment by shellscape** [comment]
@dkd-thoma unfortunately, there's too little information here for us to help you. we're migrating this plugin to the new plugins monorepo at https://github.com/rollup/plugins. If this issue is still valid, please reopen your issue at the new repo _and please make sure to fill out the appropriate issue template in full._ We're closing this issue now as part of the migration.
